name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:

  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Setup Python v${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry package
        run: |
          python -m pip install -U pip
          pip install poetry

      - name: Install packages
        run: |
          poetry install

      - name: Run tests
        run: |
          python -m pytest -vvv

  python-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install black
        run: |
          python -m pip install -U pip
          pip install poetry
          poetry install

      - name: Format Python files with black
        run: |
          black --check .

  python-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install flake8
        run: |
          python -m pip install -U pip
          pip install poetry
          poetry install

      - name: Lint Python files with flake8
        run: |
          flake8 --ignore=E501,W503,W605 open_geo_engine/
